// Code generated by protoc-gen-go.
// source: protomsg.proto
// DO NOT EDIT!

/*
Package protomsg is a generated protocol buffer package.

It is generated from these files:
	protomsg.proto

It has these top-level messages:
	HeartReq
	HeartRes
*/
package protomsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HeartReq struct {
	SID              *string `protobuf:"bytes,1,req,name=SID" json:"SID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HeartReq) Reset()                    { *m = HeartReq{} }
func (m *HeartReq) String() string            { return proto.CompactTextString(m) }
func (*HeartReq) ProtoMessage()               {}
func (*HeartReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HeartReq) GetSID() string {
	if m != nil && m.SID != nil {
		return *m.SID
	}
	return ""
}

type HeartRes struct {
	SID              *string `protobuf:"bytes,1,req,name=SID" json:"SID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HeartRes) Reset()                    { *m = HeartRes{} }
func (m *HeartRes) String() string            { return proto.CompactTextString(m) }
func (*HeartRes) ProtoMessage()               {}
func (*HeartRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HeartRes) GetSID() string {
	if m != nil && m.SID != nil {
		return *m.SID
	}
	return ""
}

func init() {
	proto.RegisterType((*HeartReq)(nil), "protomsg.HeartReq")
	proto.RegisterType((*HeartRes)(nil), "protomsg.HeartRes")
}

func init() { proto.RegisterFile("protomsg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 71 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0xcf, 0x2d, 0x4e, 0xd7, 0x03, 0x33, 0x84, 0x38, 0x60, 0x7c, 0x25, 0x71, 0x2e, 0x0e, 0x8f,
	0xd4, 0xc4, 0xa2, 0x92, 0xa0, 0xd4, 0x42, 0x21, 0x6e, 0x2e, 0xe6, 0x60, 0x4f, 0x17, 0x09, 0x46,
	0x05, 0x26, 0x0d, 0x4e, 0x24, 0x89, 0x62, 0x14, 0x09, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbe,
	0x97, 0x52, 0xd4, 0x4c, 0x00, 0x00, 0x00,
}
